name: Deploy_backend

on:
    push:
        branches: [main]
        paths:
            - 'backend/**'

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: GetJamieResumeCounter
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  DOTNET_VERSION: '8.0.x'  # Updated to .NET 8

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v2
      with:
        auth-type: SERVICE_PRINCIPAL
        client-id: ${{ secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{ secrets.AZURE_TENANT_ID}}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run unit test'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/tests'
        dotnet test

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api/output'
