name: deploy_frontend
# Deoloys when push is made from frontend folder

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.52.0
        inlineScript: |
            az storage blob upload-batch --account-name getjamieresumecounter --auth-mode login -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.52.0
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azureresume" --name "azureresumejpryce (azureresume/azureresumejpryce)" --resource-group "cloud-shell-storage-eastus"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()